// <auto-generated />
namespace RoomsAndSpacesManagerDesktop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addRowNumberInRaSM_Rooms_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRowNumberInRaSM_Rooms_3));
        
        string IMigrationMetadata.Id
        {
            get { return "202206021429534_addRowNumberInRaSM_Rooms_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
